-- =============================================================================
-- Booking Lapangan HAM — Supabase Postgres Migration
-- Schema, triggers, and Row Level Security for the Next.js migration.
--
-- Source of truth for the database structure. Applied to Supabase via the
-- Supabase MCP `apply_migration` tool (not the SQL editor) during the
-- migration. Idempotent where practical so it can be re-run safely.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Custom Types (Enums)
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('admin', 'customer');
  end if;
  if not exists (select 1 from pg_type where typname = 'booking_status') then
    create type public.booking_status as enum (
      'pending', 'dp_paid', 'payment_2_pending', 'paid', 'confirmed', 'cancelled'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'payment_type') then
    create type public.payment_type as enum ('dp', 'final');
  end if;
end$$;

-- -----------------------------------------------------------------------------
-- 2. Tables
-- -----------------------------------------------------------------------------

-- 2A. profiles — synced 1:1 with auth.users via on_auth_user_created trigger.
create table if not exists public.profiles (
  id          uuid primary key references auth.users on delete cascade,
  name        text not null,
  email       text,
  phone       text,
  role        public.user_role not null default 'customer',
  created_at  timestamptz not null default timezone('utc'::text, now())
);

alter table public.profiles
  add column if not exists email text;

-- 2B. fields — bookable venues.
create table if not exists public.fields (
  id          bigint generated by default as identity primary key,
  name        text not null,
  price       numeric(10, 2) not null,
  address     text,
  status      text not null default 'active' check (status in ('active', 'inactive')),
  created_at  timestamptz not null default timezone('utc'::text, now()),
  updated_at  timestamptz not null default timezone('utc'::text, now())
);

-- 2C. bookings — reservations with two-stage payment lifecycle.
create table if not exists public.bookings (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles(id) on delete cascade,
  field_id      bigint not null references public.fields(id) on delete cascade,
  booking_date  date not null,
  start_time    time without time zone not null,
  end_time      time without time zone not null,
  price         numeric(10, 2) not null,
  dp_amount     numeric(10, 2) not null,
  status        public.booking_status not null default 'pending',
  created_at    timestamptz not null default timezone('utc'::text, now()),
  updated_at    timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_bookings_user_id on public.bookings (user_id);
create index if not exists idx_bookings_field_id on public.bookings (field_id);
create index if not exists idx_bookings_date on public.bookings (booking_date);
create index if not exists idx_bookings_status on public.bookings (status);

-- 2D. payments — receipts for each payment stage (dp / final).
create table if not exists public.payments (
  id            bigint generated by default as identity primary key,
  booking_id    bigint not null references public.bookings(id) on delete cascade,
  amount        numeric(10, 2) not null,
  payment_type  public.payment_type not null,
  receipt_url   text not null,
  status        text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at    timestamptz not null default timezone('utc'::text, now()),
  updated_at    timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_payments_booking_id on public.payments (booking_id);

-- -----------------------------------------------------------------------------
-- 3. Functions & Triggers
-- -----------------------------------------------------------------------------

-- 3A. handle_new_user — populate public.profiles when an auth user is created.
--     SECURITY DEFINER with a pinned, empty search_path to prevent search-path
--     injection (Supabase security best practice). All object references are
--     fully schema-qualified.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, email, phone, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', 'User'),
    new.email,
    new.raw_user_meta_data ->> 'phone',
    'customer'
  );
  return new;
end;
$$;

update public.profiles as p
set email = u.email
from auth.users as u
where p.id = u.id
  and u.email is not null
  and p.email is distinct from u.email;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 3B. prevent_double_booking — reject overlapping, non-cancelled reservations
--     for the same field/date at the database level. OVERLAPS treats time
--     ranges as half-open [start, end), so adjacent slots (e.g. 08-10 and
--     10-12) do not conflict.
create or replace function public.prevent_double_booking()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  conflict_count int;
begin
  if new.status = 'cancelled' then
    return new;
  end if;

  select count(*) into conflict_count
  from public.bookings
  where field_id = new.field_id
    and booking_date = new.booking_date
    and status <> 'cancelled'
    and id <> coalesce(new.id, -1)
    and (new.start_time, new.end_time) overlaps (start_time, end_time);

  if conflict_count > 0 then
    raise exception 'DoubleBookingException: Slot waktu pada tanggal ini telah dibooking oleh pelanggan lain.';
  end if;

  return new;
end;
$$;

drop trigger if exists before_booking_upsert on public.bookings;
create trigger before_booking_upsert
  before insert or update on public.bookings
  for each row execute function public.prevent_double_booking();

-- 3C. set_updated_at — keep updated_at columns fresh on UPDATE.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists set_fields_updated_at on public.fields;
create trigger set_fields_updated_at
  before update on public.fields
  for each row execute function public.set_updated_at();

drop trigger if exists set_bookings_updated_at on public.bookings;
create trigger set_bookings_updated_at
  before update on public.bookings
  for each row execute function public.set_updated_at();

drop trigger if exists set_payments_updated_at on public.payments;
create trigger set_payments_updated_at
  before update on public.payments
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- 4. Helper: is_admin() — SECURITY DEFINER lookup used by RLS policies to
--    avoid recursive RLS evaluation on public.profiles.
-- -----------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = ''
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

-- -----------------------------------------------------------------------------
-- 5. Row Level Security
--    Enable RLS on every public table and define per-operation policies scoped
--    to the authenticated role (and anon where public read is intended).
-- -----------------------------------------------------------------------------

-- 5A. profiles
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles
  for select to authenticated
  using ((select auth.uid()) = id or public.is_admin());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

-- INSERT is handled exclusively by the handle_new_user trigger (SECURITY
-- DEFINER); no direct client INSERT policy is granted by design.

-- 5B. fields — publicly readable; only admins write.
alter table public.fields enable row level security;

drop policy if exists "fields_select_public" on public.fields;
create policy "fields_select_public" on public.fields
  for select to anon, authenticated
  using (true);

drop policy if exists "fields_insert_admin" on public.fields;
create policy "fields_insert_admin" on public.fields
  for insert to authenticated
  with check (public.is_admin());

drop policy if exists "fields_update_admin" on public.fields;
create policy "fields_update_admin" on public.fields
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "fields_delete_admin" on public.fields;

-- 5C. bookings — owner can read/create/update own; admin full read/update.
alter table public.bookings enable row level security;

drop policy if exists "bookings_select_own_or_admin" on public.bookings;
create policy "bookings_select_own_or_admin" on public.bookings
  for select to authenticated
  using ((select auth.uid()) = user_id or public.is_admin());

drop policy if exists "bookings_insert_own" on public.bookings;
create policy "bookings_insert_own" on public.bookings
  for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "bookings_update_own_or_admin" on public.bookings;
create policy "bookings_update_own_or_admin" on public.bookings
  for update to authenticated
  using ((select auth.uid()) = user_id or public.is_admin())
  with check ((select auth.uid()) = user_id or public.is_admin());

-- 5D. payments — owner (via booking) can read/create own; admin full read/update.
alter table public.payments enable row level security;

drop policy if exists "payments_select_own_or_admin" on public.payments;
create policy "payments_select_own_or_admin" on public.payments
  for select to authenticated
  using (
    public.is_admin()
    or exists (
      select 1 from public.bookings b
      where b.id = payments.booking_id and b.user_id = (select auth.uid())
    )
  );

drop policy if exists "payments_insert_own" on public.payments;
create policy "payments_insert_own" on public.payments
  for insert to authenticated
  with check (
    exists (
      select 1 from public.bookings b
      where b.id = payments.booking_id and b.user_id = (select auth.uid())
    )
  );

drop policy if exists "payments_update_admin" on public.payments;
create policy "payments_update_admin" on public.payments
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- 6. Lock down SECURITY DEFINER / trigger functions
--    Trigger functions still fire regardless of EXECUTE grants; they must not
--    be exposed as PostgREST RPCs. is_admin() runs inside RLS policies as the
--    policy owner, so it needs no public RPC surface.
-- -----------------------------------------------------------------------------
revoke execute on function public.handle_new_user() from anon, authenticated, public;
revoke execute on function public.prevent_double_booking() from anon, authenticated, public;
revoke execute on function public.set_updated_at() from anon, authenticated, public;
revoke execute on function public.is_admin() from anon, public;
grant execute on function public.is_admin() to authenticated;

-- -----------------------------------------------------------------------------
-- 7. Concurrency-safe double-booking prevention (defense in depth)
--    The prevent_double_booking trigger guards sequential inserts, but a
--    check-then-insert has a race window under concurrent transactions. A GiST
--    EXCLUDE constraint closes it atomically at the schema level.
-- -----------------------------------------------------------------------------
create extension if not exists btree_gist with schema extensions;

-- Generated half-open [start, end) timestamp range from booking_date +
-- start_time/end_time (the spec's columns are left unchanged).
alter table public.bookings
  add column if not exists slot_range tsrange
  generated always as (
    tsrange(
      (booking_date + start_time)::timestamp,
      (booking_date + end_time)::timestamp,
      '[)'
    )
  ) stored;

-- No two non-cancelled bookings for the same field may overlap. Adjacent slots
-- (08-10, 10-12) do not overlap under half-open semantics.
alter table public.bookings drop constraint if exists bookings_no_overlap;
alter table public.bookings
  add constraint bookings_no_overlap
  exclude using gist (
    field_id with =,
    slot_range with &&
  ) where (status <> 'cancelled');

-- -----------------------------------------------------------------------------
-- 8. Admin transactional booking operations
--    These RPCs keep booking/payment status changes atomic for admin approvals.
--    They are SECURITY INVOKER functions, check public.is_admin(), and run as a
--    single Postgres transaction when called through Supabase RPC.
-- -----------------------------------------------------------------------------
create or replace function public.admin_approve_dp(p_booking_id bigint)
returns table (booking_id bigint, user_id uuid)
language plpgsql
set search_path = ''
as $$
declare
  v_booking public.bookings%rowtype;
  v_payment_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Forbidden: admin role required';
  end if;

  select * into v_booking
  from public.bookings
  where id = p_booking_id and status = 'pending'
  for update;

  if not found then
    raise exception 'BookingNotPending: booking is not pending or does not exist';
  end if;

  select p.id into v_payment_id
  from public.payments as p
  where p.booking_id = p_booking_id
    and p.payment_type = 'dp'
    and p.status = 'pending'
  order by p.created_at desc
  limit 1
  for update;

  if v_payment_id is null then
    raise exception 'PendingDPPaymentNotFound: no pending DP payment found';
  end if;

  update public.payments set status = 'approved' where id = v_payment_id;
  update public.bookings set status = 'dp_paid' where id = p_booking_id;

  return query select v_booking.id, v_booking.user_id;
end;
$$;

create or replace function public.admin_approve_final_payment(p_booking_id bigint)
returns table (booking_id bigint, user_id uuid)
language plpgsql
set search_path = ''
as $$
declare
  v_booking public.bookings%rowtype;
  v_payment_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Forbidden: admin role required';
  end if;

  select * into v_booking
  from public.bookings
  where id = p_booking_id and status = 'payment_2_pending'
  for update;

  if not found then
    raise exception 'BookingFinalPaymentNotPending: booking is not waiting for final payment or does not exist';
  end if;

  select p.id into v_payment_id
  from public.payments as p
  where p.booking_id = p_booking_id
    and p.payment_type = 'final'
    and p.status = 'pending'
  order by p.created_at desc
  limit 1
  for update;

  if v_payment_id is null then
    raise exception 'PendingFinalPaymentNotFound: no pending final payment found';
  end if;

  update public.payments set status = 'approved' where id = v_payment_id;
  update public.bookings set status = 'confirmed' where id = p_booking_id;

  return query select v_booking.id, v_booking.user_id;
end;
$$;

create or replace function public.admin_cancel_booking(p_booking_id bigint)
returns table (booking_id bigint, previous_status public.booking_status)
language plpgsql
set search_path = ''
as $$
declare
  v_booking public.bookings%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Forbidden: admin role required';
  end if;

  select * into v_booking
  from public.bookings
  where id = p_booking_id and status <> 'cancelled'
  for update;

  if not found then
    raise exception 'BookingAlreadyCancelledOrMissing: booking is cancelled or does not exist';
  end if;

  update public.bookings set status = 'cancelled' where id = p_booking_id;
  update public.payments as p
  set status = 'rejected'
  where p.booking_id = p_booking_id and p.status = 'pending';

  return query select v_booking.id, v_booking.status;
end;
$$;

grant execute on function public.admin_approve_dp(bigint) to authenticated;
grant execute on function public.admin_approve_final_payment(bigint) to authenticated;
grant execute on function public.admin_cancel_booking(bigint) to authenticated;
revoke execute on function public.admin_approve_dp(bigint) from anon;
revoke execute on function public.admin_approve_final_payment(bigint) from anon;
revoke execute on function public.admin_cancel_booking(bigint) from anon;

-- -----------------------------------------------------------------------------
-- 9. Final RLS hardening (no self-promotion, no direct workflow tampering)
-- -----------------------------------------------------------------------------
revoke update on public.profiles from authenticated;
grant update (name, phone) on public.profiles to authenticated;

create or replace function public.calculate_booking_price_db(
  p_booking_date date,
  p_start_time time without time zone,
  p_end_time time without time zone
)
returns table (total numeric, dp numeric)
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_day int := extract(dow from p_booking_date);
  v_start int := extract(hour from p_start_time);
  v_end int := extract(hour from p_end_time);
  v_total numeric := 0;
  v_slot record;
  v_price numeric;
begin
  if extract(minute from p_start_time) <> 0 or extract(minute from p_end_time) <> 0 or v_start >= v_end then
    raise exception 'InvalidBookingSlot: invalid start/end time';
  end if;

  for v_slot in
    select * from (values
      (6, 8, null::numeric, null::numeric, 2600000::numeric),
      (8, 10, 1300000::numeric, null::numeric, 2600000::numeric),
      (10, 12, 800000::numeric, null::numeric, 1500000::numeric),
      (12, 14, 800000::numeric, null::numeric, 1500000::numeric),
      (14, 16, 1300000::numeric, 1300000::numeric, 2600000::numeric),
      (16, 18, 2000000::numeric, 2300000::numeric, 2600000::numeric),
      (18, 20, 2300000::numeric, 2500000::numeric, 2800000::numeric),
      (20, 22, 2300000::numeric, 2500000::numeric, 2800000::numeric)
    ) as slots(start_hour, end_hour, weekday_price, friday_price, weekend_price)
  loop
    if v_slot.start_hour >= v_start and v_slot.end_hour <= v_end then
      if v_day between 1 and 4 then
        v_price := coalesce(v_slot.weekday_price, v_slot.weekend_price);
      elsif v_day = 5 then
        v_price := coalesce(v_slot.friday_price, v_slot.weekend_price);
      else
        v_price := v_slot.weekend_price;
      end if;
      v_total := v_total + v_price;
    end if;
  end loop;

  if v_total <= 0 then
    raise exception 'InvalidBookingSlot: no matching price slot';
  end if;

  total := v_total;
  dp := greatest(v_total * 0.3, 500000);
  return next;
end;
$$;

create or replace function public.prevent_customer_booking_update_tampering()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is not null
    and old.user_id = (select auth.uid())
    and not public.is_admin()
  then
    if new.id is distinct from old.id
      or new.user_id is distinct from old.user_id
      or new.field_id is distinct from old.field_id
      or new.booking_date is distinct from old.booking_date
      or new.start_time is distinct from old.start_time
      or new.end_time is distinct from old.end_time
      or new.price is distinct from old.price
      or new.dp_amount is distinct from old.dp_amount
      or new.created_at is distinct from old.created_at
    then
      raise exception 'ForbiddenBookingMutation: booking details cannot be changed by customers';
    end if;

    if old.status = 'dp_paid' and new.status = 'payment_2_pending' then
      return new;
    end if;

    if old.status = 'payment_2_pending' and new.status = 'dp_paid' then
      if exists (
        select 1 from public.payments p
        where p.booking_id = old.id and p.payment_type = 'final' and p.status = 'pending'
      ) then
        raise exception 'ForbiddenBookingMutation: cannot revert after final payment is recorded';
      end if;
      return new;
    end if;

    raise exception 'ForbiddenBookingMutation: invalid customer status transition';
  end if;

  return new;
end;
$$;

drop trigger if exists prevent_customer_booking_update_tampering on public.bookings;
create trigger prevent_customer_booking_update_tampering
  before update on public.bookings
  for each row execute function public.prevent_customer_booking_update_tampering();
revoke execute on function public.prevent_customer_booking_update_tampering() from anon, authenticated, public;

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);

drop policy if exists "fields_delete_admin" on public.fields;

drop policy if exists "bookings_insert_own" on public.bookings;
create policy "bookings_insert_own" on public.bookings
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and status = 'pending'
    and price = (select total from public.calculate_booking_price_db(booking_date, start_time, end_time))
    and dp_amount = (select dp from public.calculate_booking_price_db(booking_date, start_time, end_time))
    and exists (select 1 from public.fields f where f.id = field_id and f.status = 'active')
  );

drop policy if exists "bookings_update_own_or_admin" on public.bookings;
drop policy if exists "bookings_update_admin" on public.bookings;
create policy "bookings_update_admin" on public.bookings
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "bookings_update_customer_payment_transition" on public.bookings;
create policy "bookings_update_customer_payment_transition" on public.bookings
  for update to authenticated
  using ((select auth.uid()) = user_id and status in ('dp_paid', 'payment_2_pending'))
  with check ((select auth.uid()) = user_id and status in ('dp_paid', 'payment_2_pending'));

drop policy if exists "payments_insert_own" on public.payments;
create policy "payments_insert_own" on public.payments
  for insert to authenticated
  with check (
    status = 'pending'
    and amount > 0
    and (select auth.uid())::text = (storage.foldername(receipt_url))[1]
    and exists (
      select 1 from public.bookings b
      where b.id = payments.booking_id
        and b.user_id = (select auth.uid())
        and (
          (payments.payment_type = 'dp' and b.status = 'pending' and payments.amount = b.dp_amount)
          or (payments.payment_type = 'final' and b.status = 'payment_2_pending' and payments.amount = greatest(b.price - b.dp_amount, 0))
        )
    )
  );

-- Combine admin/customer booking UPDATE policies to avoid multiple permissive
-- policy evaluation for the same role/action.
drop policy if exists "bookings_update_admin" on public.bookings;
drop policy if exists "bookings_update_customer_payment_transition" on public.bookings;
create policy "bookings_update_admin_or_customer_payment_transition" on public.bookings
  for update to authenticated
  using (
    public.is_admin()
    or ((select auth.uid()) = user_id and status in ('dp_paid', 'payment_2_pending'))
  )
  with check (
    public.is_admin()
    or ((select auth.uid()) = user_id and status in ('dp_paid', 'payment_2_pending'))
  );

-- Remove customer hard-delete. Failed/incomplete customer flows retain booking
-- history by transitioning pending bookings to cancelled instead of deleting.
drop policy if exists "bookings_delete_own_pending" on public.bookings;

create or replace function public.prevent_customer_booking_update_tampering()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is not null
    and old.user_id = (select auth.uid())
    and not public.is_admin()
  then
    if new.id is distinct from old.id
      or new.user_id is distinct from old.user_id
      or new.field_id is distinct from old.field_id
      or new.booking_date is distinct from old.booking_date
      or new.start_time is distinct from old.start_time
      or new.end_time is distinct from old.end_time
      or new.price is distinct from old.price
      or new.dp_amount is distinct from old.dp_amount
      or new.created_at is distinct from old.created_at
    then
      raise exception 'ForbiddenBookingMutation: booking details cannot be changed by customers';
    end if;

    if old.status = 'pending' and new.status = 'cancelled' then
      return new;
    end if;

    if old.status = 'dp_paid' and new.status = 'payment_2_pending' then
      return new;
    end if;

    if old.status = 'payment_2_pending' and new.status = 'dp_paid' then
      if exists (
        select 1 from public.payments p
        where p.booking_id = old.id and p.payment_type = 'final' and p.status = 'pending'
      ) then
        raise exception 'ForbiddenBookingMutation: cannot revert after final payment is recorded';
      end if;
      return new;
    end if;

    raise exception 'ForbiddenBookingMutation: invalid customer status transition';
  end if;

  return new;
end;
$$;
revoke execute on function public.prevent_customer_booking_update_tampering() from anon, authenticated, public;

drop policy if exists "bookings_update_admin_or_customer_payment_transition" on public.bookings;
create policy "bookings_update_admin_or_customer_payment_transition" on public.bookings
  for update to authenticated
  using (
    public.is_admin()
    or ((select auth.uid()) = user_id and status in ('pending', 'dp_paid', 'payment_2_pending'))
  )
  with check (
    public.is_admin()
    or ((select auth.uid()) = user_id and status in ('cancelled', 'dp_paid', 'payment_2_pending'))
  );
